-- Re-seed of the 44 production stakeholders (lost during the prod push).
-- Idempotent guard: inserts only if no stakeholder with the same name + project exists.
-- project_id resolved from project_number via subquery.

INSERT INTO public.stakeholders (project_id, name, title, department, role, email, phone, sentiment, is_primary, org)
SELECT v.project_id, v.name, v.title, v.department, v.role, v.email, v.phone, v.sentiment, v.is_primary, v.org
FROM (VALUES
  (NULL::UUID,                                                              'Morgan Brawner',     'Project Developer',                                                          'Development',     'Project Manager', 'mbrawner@esa-solar.com',          'TBD', 'Supportive', TRUE,  'ESA Solar'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0008'),   'Scott Sukits',       'Regional Director Facilities/Engineering, Control Systems & Energy Mgmt',  'Facilities',       'Evaluator',       'scott.sukits@adventhealth.com',   'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0008'),   'Ben Dale',           'Director of Operations',                                                     'Operations',       'Evaluator',       'ben.dale@adventhealth.com',       'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0008'),   'Deanna Peter',       'HR Director',                                                                'HR/Administrative','Influencer',      'deeana.peter@adventhealth.com',   'TBD', 'Neutral',    FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0008'),   'Kirstie Questell',   'Chief Financial Officer',                                                    'Finance',          'Evaluator',       'kirstie.questell@adventhealth.com','TBD', 'Neutral',    FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0015'),   'Jeffery Bates',      'Executive Director of Facilities',                                           'Facilities',       'Decision Maker',  'jeffery.bates@adventhealth.com',  'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0015'),   'Anwar Bowes',        'Director of Operations',                                                     'Operations',       'Evaluator',       'anwar.bowes@adventhealth.com',    'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0015'),   'Tim Williams',       'Chief Operating Officer',                                                    'Operations',       'Decision Maker',  'tim.williams@adventhealth.com',   'TBD', 'Neutral',    TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0012'),   'Mark Rathbun',       'Chief Financial Officer',                                                    'Finance',          'Evaluator',       'mark.rathbun@adventhealth.com',   'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0012'),   'Jefferson Santos',   'Director of Operations',                                                     'Operations',       'Evaluator',       'jefferson.santos@adventhealth.com','TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0012'),   'Clifton Scott',      'Chief Operating Officer',                                                    'Operations',       'Decision Maker',  'clifton.scott@adventhealth.com',  'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0012'),   'John Newman',        'Executive Director of Facilities',                                           'Facilities',       'Evaluator',       'john.c.newman@adventhealth.com',  'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0012'),   'Wally Deaquino',     'Chief Executive Officer',                                                    'Operations',       'Decision Maker',  'wally.deaquino@adventhealth.com', 'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0009'),   'Jacob Cook',         'Chief Operating Officer',                                                    'Operations',       'Decision Maker',  'jacob.cook@adventhealth.com',     'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0009'),   'Rebecca Mcintyre',   'Director of Ancillary Services',                                             'Operations',       'Evaluator',       'rebecca.mcintyre@adventhealth.com','TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0009'),   'Michael Prentice',   'Director Global Supply Chain',                                               'Operations',       'Evaluator',       'michael.prentice@adventhealth.com','TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0009'),   'Jeff Chilson',       'Chief Financial Officer',                                                    'Finance',          'Evaluator',       'jeff.chilson@adventhealth.com',   'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0004'),   'Lisa Kelley',        'Director of Performance Excellence',                                         'Operations',       'Evaluator',       'lisa.kelley@adventhealth.com',    'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0004'),   'Dawn Richards',      'Associate VP of Finance',                                                    'Finance',          'Evaluator',       'Dawn.L.Richards@AdventHealth.com','TBD', 'Concerned',  FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0004'),   'Jocelyn Krise',      'Executive Director of Rehabilitation',                                       'Operations',       'Influencer',      'jocelyn.krise@adventhealth.com',  'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0004'),   'David Gordon',       'Executive Director of Operations',                                           'Operations',       'Evaluator',       'david.gordon@adventhealth.com',   'TBD', 'Neutral',    FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0004'),   'David Musser',       'Engineering Supervisor',                                                     'Facilities',       'Evaluator',       'david.musser@adventhealth.com',   'TBD', 'Neutral',    FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0006'),   'Justin Watson',      'Director of Operations & COO (acting)',                                      'Operations',       'Decision Maker',  'justin.watson@adventhealth.com',  'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0006'),   'Christina Miller',   'Director Institute for Lifestyle Medicine',                                  'Facilities',       'Evaluator',       'christina.miller6@adventhealth.com','TBD', 'Neutral',    FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0006'),   'Juan Garcia',        'Director of Engineering',                                                    'Facilities',       'Evaluator',       'juan.garcia@adventhealth.com',    'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0001'),   'Kevin Poole',        'Chief Operating Officer',                                                    'Operations',       'Decision Maker',  'kevin.poole@adventhealth.com',    'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0001'),   'Kurt Azevedo',       'Director of Engineering',                                                    'Facilities',       'Evaluator',       'kurt.azevedo@adventhealth.com',   'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0001'),   'Abigail Shelton',    'Finance Director',                                                           'Finance',          'Evaluator',       'abigail.shelton@adventhealth.com','TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0001'),   'Kathleen Gdula',     'Director of Operations',                                                     'Operations',       'Evaluator',       'kathleen.gdula@adventhealth.com', 'TBD', 'Neutral',    FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0007'),   'Jeffrey Brownlow',   'Executive Director of Operations',                                           'Operations',       'Evaluator',       'jeffrey.brownlow@adventhealth.com','TBD', 'Concerned',  FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0007'),   'Joshua Pinion',      'Director of Facilities',                                                     'Facilities',       'Evaluator',       'joshua.pinion@adventhealth.com',  'TBD', 'Neutral',    FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0014'),   'Susan Ward',         'Supply Chain Director',                                                      'Operations',       'Decision Maker',  'susan.e.ward@adventhealth.com',   'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0014'),   'Nicole O''Keefe',    'Director of Operations',                                                     'Operations',       'Evaluator',       'nicole.acosta@adventhealth.com',  'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0014'),   'Mark Chapoton',      'Facilities Engineering Director',                                            'Facilities',       'Evaluator',       'mark.chapoton@adventhealth.com',  'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0014'),   'Nick Papa',          'Director for Support Services',                                              'Operations',       'Evaluator',       'nick.papa@adventhealth.com',      'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0014'),   'Zachary Crane',      'Chief Operating Officer',                                                    'Operations',       'Decision Maker',  'zachary.crane@adventhealth.com',  'TBD', 'Neutral',    TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0005'),   'Douglas Colburn',    'Chief Operating Officer',                                                    'Operations',       'Decision Maker',  'douglas.colburn@adventhealth.com','TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0005'),   'John Crouch',        'Admin Director of Engineering — Sustainability Counsel',                     'Facilities',       'Evaluator',       'john.crouch@adventhealth.com',    'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0005'),   'Aaron Patterson',    'Leadership Resident — Sustainability Counsel',                               'Sustainability',   'Influencer',      'aaron.patterson@adventhealth.com','TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0010'),   'Jeffrey Bates',      'Executive Director for Engineering & Facilities',                            'Facilities',       'Decision Maker',  'jeffery.bates@adventhealth.com',  'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0010'),   'Kenneth Zill',       'Chief Financial Officer',                                                    'Finance',          'Evaluator',       'kenneth.zill@adventhealth.com',   'TBD', 'Supportive', FALSE, 'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0017'),   'Jake Miller',        'Director of Operations',                                                     'Operations',       'Decision Maker',  'jake.miller@adventhealth.com',    'TBD', 'Supportive', TRUE,  'AdventHealth'),
  ((SELECT id FROM public.projects WHERE project_number='21460-FL-0017'),   'Vincent David',      'Facilities Manager',                                                         'Facilities',       'Influencer',      'vincent.david@adventhealth.com',  'TBD', 'Supportive', FALSE, 'AdventHealth')
) AS v(project_id, name, title, department, role, email, phone, sentiment, is_primary, org)
WHERE NOT EXISTS (
  SELECT 1 FROM public.stakeholders s
  WHERE s.name = v.name
    AND ((s.project_id IS NULL AND v.project_id IS NULL) OR s.project_id = v.project_id)
);
